//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
<<<<<<< HEAD:WebApplication1/WebApplication1/WebForm3.aspx.designer.cs
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1 {
    
    
    public partial class WebForm3 {
=======
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{


    public partial class ErrorPage
    {
>>>>>>> 96ae9edb0255ba1a560250d2bd64eac43f34f2f0:WebApplication1/WebApplication1/ErrorPage.aspx.designer.cs
    }
}
